[package]
name = "drakoon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
lalrpop-util = "0.22.2"
logos = "0.15.0"

[build-dependencies]
lalrpop = "0.22.2"
